# Deploy PODs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-web-app
  labels:
    app: ocr-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-web-app
  template:
    metadata:
      labels:
        app: ocr-web-app
    spec:
      containers:
      - name: ocr-web-app
        image: jp.icr.io/mile-iisc/ocr-web-app:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: MONGODB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: endpoint
              optional: true
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwtsecret
              key: jwtkey
              optional: true
---
# Expose as service
apiVersion: v1
kind: Service
metadata:
  name: ocr-web-app
  namespace: default
  labels:
    app: ocr-web-app
spec:
  type: LoadBalancer
  selector:
    app: ocr-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
