# Deploy PODs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-web-app
  labels:
    app: ocr-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-web-app
  template:
    metadata:
      labels:
        app: ocr-web-app
    spec:
      containers:
      - name: ocr-web-app
        image: jp.icr.io/mile-iisc/ocr-web-app:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwtsecret
              key: jwtkey
        - name: OBJECT_STORAGE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: objectstorage-secret
              key: endpoint
        - name: OBJECT_STORAGE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: objectstorage-secret
              key: accessKeyId
        - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: objectstorage-secret
              key: secretAccessKey
        - name: RUN_OCR_ADDRESS
          valueFrom:
            secretKeyRef:
              name: ocrengine-secret
              key: address
        - name: RUN_OCR_PORT
          valueFrom:
            secretKeyRef:
              name: ocrengine-secret
              key: port
        - name: COUCH_DB_HOST
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchDbHost
        - name: COUCH_DB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchDbAdminUsername
        - name: COUCH_DB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchDbAdminPassword
        - name: COUCH_DB_PROVIDER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchDbProvider
---
# Expose as service
apiVersion: v1
kind: Service
metadata:
  name: ocr-web-app
  namespace: default
  labels:
    app: ocr-web-app
spec:
  type: LoadBalancer
  selector:
    app: ocr-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
